# Generated by Django 4.0 on 2021-12-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201122_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=50)),
                ('desc1', models.CharField(max_length=50)),
                ('test2', models.CharField(max_length=50)),
                ('desc2', models.CharField(max_length=50)),
                ('test3', models.CharField(max_length=50)),
                ('desc3', models.CharField(max_length=50)),
                ('test4', models.CharField(max_length=50)),
                ('desc4', models.CharField(max_length=50)),
                ('test5', models.CharField(max_length=50)),
                ('desc5', models.CharField(max_length=50)),
                ('test6', models.CharField(max_length=50)),
                ('desc6', models.CharField(max_length=50)),
                ('test7', models.CharField(max_length=50)),
                ('desc7', models.CharField(max_length=50)),
                ('test8', models.CharField(max_length=50)),
                ('desc8', models.CharField(max_length=50)),
                ('test9', models.CharField(max_length=50)),
                ('desc9', models.CharField(max_length=50)),
                ('test10', models.CharField(max_length=50)),
                ('desc10', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.patient')),
            ],
        ),
    ]
