# Generated by Django 4.0 on 2021-12-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
    ]
